
cereal <- read.csv("C:/Users/Daniel/Google Drive/Stuff/Daniel/School/ANLY 6100 _ 2020.09/Assignment 1/cereal.csv") 
# cereal <- read.csv("C:/Users/suu/downloads/cereal.csv")
cereal
attach(cereal)
ls(cereal)

# name: Name of cereal
# mfr: Manufacturer of cereal (A = American Home Food Products, G = General Mills, K =
# Kellogg’s, N = Nabisco, P = Post, Q = Quaker Oats, R = Ralston Purina)
# type: hot or cold (H = Hot, C = Cold)
# calories: calories per serving
# protein: grams of protein per serving
# fat: grams of fat per serving
# sodium: milligrams of sodium per serving
# fiber: grams of dietary fiber per serving
# carbo: grams of complex carbohydrates per serving
# sugars: grams of sugars per serving
# potass: milligrams of potassium per serving
# vitamins: amount of vitamins and minerals present in the cereal (0%, 25%, or 100%,
# indicating the typical percentage of FDA recommended)
# shelf: display shelf (1, 2, or 3, counting from the floor)
# weight: weight in ounces of one serving
# cups: number of cups in one serving
# rating: a rating of the cereals (possibly from Consumer Reports?)



# 1 - (5 points) 
# Remove an existing variable: The last variable in the data set, rating, is of
# unknown origin. Since we don’t know who was rating the cereals or where this rating
# came from for sure, remove it from the data set without creating an entirely new data
# set.
cereal[,-16]


# 2 - (15 points) 
# Create new variables:
# a. Create a new variable, cpc, where cpc is the calories per cup of each cereal
cpc <- cereal$calories/cereal$cup
cpc


# b. Create a new variable, mfr2, where mfr2 is “Kelloggs” if the manufacturer of a
# cereal is Kellogg’s, “GM” if the manufacturer is General Mills, and “Other” if the
# manufacturer is not Kellogg’s or General Mills.
mfr2 <- ifelse(cereal$mfr =="K","Kellogs",ifelse(cereal$mfr =="G","GM","Other"))
mfr2


#3 - (10 points) 
# Plot a histogram in R: Start by plotting a histogram of the calories of all
# cereals. Make sure the histogram:
# a. Is dark blue
# b. Has the x-axis labeled “Number of Calories”
# c. Has the y-axis labeled “Number of Cereals”
# d. Is titled “Calories in Common Cereals” in dark red
# e. Includes labels of how many cereals are in each bar of the histogram

hist(cereal$calories
    ,main = paste("")
    ,xlab="Number of Calories"
    ,ylab = "Number of Cereals"
    ,col = "darkblue"
    ,labels = TRUE)
title(main = list("Calories in Common Cereals",col="darkred"))


# 4 - (10 points)
# Plot a boxplot in R: Create a boxplot that separates out the number of
# complex carbohydrates in a serving (y-axis) by the type of cereal (the x-axis). One of
# your fellow cereal researchers believes hot cereals have more carbs per serving than
# cold cereals do. Does your boxplot support this? Explain your answer.

boxplot(cereal$type
       ,cereal$carbo
       ,names = TRUE)
# Based on the box plot, cold cereals have more carbs than hot cereal.


# 5 - (15 points) 
# Plot a more difficult boxplot in R: Create a boxplot that separates out the
# calories per cup (y-axis) by type of cereal (the x-axis). Make sure the boxplot:
# a. Is adjusted for width (that is, the width of the boxplot indicates how many
# cereals are hot vs. cold )
# b. Has the x-axis labeled “Type of Cereal (C = Cold, H = Hot)”
# c. Has the y-axis labeled “Calories Per Cup”
# d. Only shows the cereals with calories per cup between 0 and 300

boxplot(cereal$type
       ,cpc
       ,varwidth = TRUE
       ,xlab = "Type of Cereal (C = Cold, H = Hot)"
       ,ylab = "Calories Per Cup"
       ,subset = cpc <= 300
       ,names = TRUE
        )


# 6 - (25 points) 
# Answer the following questions about the data set. For each question,
# include some evidence gathered from R that supports your conclusion. Note this can
# be any evidence, as long as it was generated by R and agrees with your answer! For
# example, if you were asked to find the maximum value of a variable called “Z”, you
# could use the R code max(Z) or you could show the summary of the variable Z where
# the maximum value is listed.
# a. Which cereal has the highest number of calories per cup?

df_cpc <- data.frame(cereal$name,cpc)
df_cpc
summary(df_cpc)


# b. How many of the cereals in this data set were manufactured by Post?

sum(ifelse(cereal$mfr == "P",1,0))


# c. What percentage of the cereals in this data set were not manufactured by either
# Kellogg’s or General Mills?

sum(!(cereal$mfr %in% c("K","G"))) / sum(summary(cereal$mfr))


# d. How many cereals in this data set contain no fiber?

sum(cereal$fiber == 0)


# e. Which variables in this data set were not loaded into R as numeric variables?

str(cereal)


# 7 - (20 points) 
# Conditional Probability: Answer the following questions about probability
# using the cereal data set.
# a. What is the probability a random cereal (in this data set) has at least 100
# milligrams of potassium per serving?

sum(cereal$potass >= 100) / sum(summary(cereal$mfr))


# b. What is the probability a random cereal (in this data set) has at least 100
# milligrams of potassium per serving given it was manufactured by Post?

sum(ifelse(cereal$mfr == "P",cereal$potass,0) >= 100) / sum(ifelse(cereal$mfr == "P",cereal$potass,0) > 0)

# c. Consider your answers to parts (a), (b), and 6(b) above. Do you think Post is
# better than other manufacturers about including potassium in their cereals or
# not? Explain your answer.

# Post is slighlty better than other manufacturers about including potassium in 
# their cereals because the probability that any cereal includes at least 100 mg
# of Potassium is 41.5% and the probability that a Post cereal includes at least
# 100 mg of Potassium is 44.4%

# 8 - 
# Did you work with anyone on this assignment? If so, include their name(s) here.
# No